name: dart_firebase_admin
description: A Firebase Admin SDK implementation for Dart.
version: 0.0.1
homepage: "https://github.com/invertase/dart_firebase_admin"

dependencies:
  firebaseapis: ^0.1.0+1
  googleapis_auth: ^1.3.0

environment:
  sdk: ">=2.15.0 <3.0.0"